
name: "Code Analysis"
on: [ push ]


jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Get Flutter Env
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    - run: flutter --version

    - name: Code Analysis
      working-directory: client-app
      run: flutter analyze

    - name: Unit Testing
      working-directory: client-app
      run: flutter test
